### ISSUE TITLE
Update chart to use helm release namespace

### ISSUE THREAD

**Issue by alex-bezek** [honeycombio/helm-charts#146]
**Is your feature request related to a problem? Please describe.**

We utilize the helm templating engine to generate our manifests which we then check in and apply via kubectl at a later time. Right now, this chart doesn't inject the helm release namespace into the resources' metadata. It instead relies on the underlying kubectl client having a namespace flag specified. 

**Describe the solution you'd like**

A common pattern is to include this in the templates
```
metadata:
    namespace: {{ .Release.Namespace }}
```

This lets you still use the existing way of applying via helm or kubectl and passing the namespace flag, but also allows generating templates with the namespace dictated in the yaml. 

**Describe alternatives you've considered**

We could work around this issue by writing code so our deployment pipeline can take the namespace and apply it with kubectl. Other charts we use specify this namespace, so it would be nice if they were consistent.

**Additional context**
There was a long conversation about this [here](https://github.com/helm/helm/issues/5465). It was ultimately closed as they won't dictate one way or the other. There are lots of issues that link to it though where others have added in this config.

Let me know your thoughts on this particular matter. If you approve, we can do the PR. Thanks for your consideration!

**Comment by MikeGoldsmith** [comment]
Hi @alex-bezek - I've reviewed your suggestion and think it's something we would like to add. If you're up to providing a PR, we're always welcoming of community contributions. Otherwise we'll add it to our backlog for prioritisation 👍🏻 

The only concern I have regarding implementation, is to ensure the a nil / empty value us handled. It would be great to include the test cases as part of the PR.

**Comment by alex-bezek** [comment]
@MikeGoldsmith I created a PR here https://github.com/honeycombio/helm-charts/pull/155

> The only concern I have regarding implementation, is to ensure the a nil / empty value us handled. It would be great to include the test cases as part of the PR.

I don't see any testing infrastructure setup in this repo. This value is a default included one with helm that is always the current context which should be default not nil in the non-set value. I don't think it can ever really be nil. If you would like a test case for that and want to point me in the right direction for how to setup helm tests, I could take a stab.
