### ISSUE TITLE
Do we need `/x/alive` for Refinery readiness check?

### ISSUE THREAD

**Issue by bixu** [honeycombio/helm-charts#150]
https://github.com/honeycombio/helm-charts/blob/555231a5ffaf59c815397007a48726f434b81132/charts/refinery/templates/deployment.yaml#L84

I'm comparing the line above to the docs: https://docs.honeycomb.io/manage-data-volume/refinery/scale-and-troubleshoot/#xalive

**Comment by MikeGoldsmith** [comment]
The Refinery API only has the `/alive` endpoint. The docs should be updated to remove the `/x/alive` endpoint.

**Comment by MikeGoldsmith** [comment]
For now, I think using the `/x/alive` endpoint is not a good idea. We have seen refinery struggle to cope with irregular cluster topology changes and this could exacerbate the problem. Plus, in the case there was a Honeycomb API outage, we wouldn't want a refinery cluster to take itself down - the cluster nodes should be stable and utilise other tools (eg retries and memory limiting) to protect itself until it can deliver telemetry to Honeycomb.
