### ISSUE TITLE
Update HPA's to autoscaling/v2 as autoscaling/v2beta2 is deprecated in k8s 1.23, and removed in 1.26

### ISSUE THREAD

**Issue by robiball** [honeycombio/helm-charts#212]
**Is your feature request related to a problem? Please describe.**
The HPA templates are using the deprecated autoscaling/v2beta1 and autoscaling/v2beta2 versions. Ideally these would be updated to autoscaling/v2. 

**Describe the solution you'd like**
Update the templates the HPA templates to the autoscaling/v2 format. Very minimal changes are required to do this. 

**Describe alternatives you've considered**
Could potentially introduce a new variable in the values file to allow using an older version of the HPA resource if further backwards compatability is required.

**Additional context**
Happy to PR in either approach if that would be helpful.

**Comment by TylerHelmuth** [comment]
@robiball thanks for bringing this to our attention. With the kubernetes community dropping support for 1.22 and the current implementation breaking support with 1.26 we are good with those versions being updated directly to `autoscaling/v2`.  Would you like to submit a PR for that?

**Comment by robiball** [comment]
Yep, will send it over tomorrow!

**Comment by robiball** [comment]
Hey @TylerHelmuth, I've created that PR now. I have included another update in there around the ordering of the resource metrics whilst I was in there. If you need me to pull that into a separate PR/issue just let me know.

**Comment by robiball** [comment]
Thanks for merging the PR. How often do you publish new versions of the charts?

**Comment by TylerHelmuth** [comment]
@robiball we are working on pushing releases for opentelemetry-collector and refinery right now.

**Comment by robiball** [comment]
Fantastic, thank you!

**Comment by TylerHelmuth** [comment]
@robiball charts released.
