### ISSUE TITLE
Reorder the Resource metrics to have memory before CPU 

### ISSUE THREAD

**Issue by robiball** [honeycombio/helm-charts#216]
**Is your feature request related to a problem? Please describe.**
HPA objects incorrectly show as `out of sync` in ArgoCD if the metrics ordering doesn't match what's expected. This has been resolved in the `opentelemetry-collector` chart (see here: https://github.com/honeycombio/helm-charts/pull/164), but is still present in the `refinery` and `secure-tenancy` charts.

**Describe the solution you'd like**
Reorder the resouce metrics in the `refinery` and `secure-tenancy` charts to have memory before cpu.

**Additional context**
Happy to PR this in if you agree with it.

**Comment by TylerHelmuth** [comment]
@robiball thanks for the details.  Would love a PR to fix this.

**Comment by robiball** [comment]
https://github.com/honeycombio/helm-charts/pull/217 :)
