### ISSUE TITLE
Update Refinery chart to use 0s for ConfigReloadInterval

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/helm-charts#280]
The default value for Refinery's config value `General` `ConfigReloadInterval` is intended for use in a world where the configuration might be hot reloaded. Most K8s configurations simply restart the pod when this happens, so there's no need to invoke this mechanism. We should set the value in our chart to 0s to disable it when we update the chart to Refinery 2.1.

**Comment by TylerHelmuth** [comment]
I thought the chart set `LiveReload` to `false` by default, but it actually uses `true`.  This means by default the chart installs a refinery instance that expects a reload interval.  We don't need to make this change like I thought.
