### ISSUE TITLE
Refinery pods do not restart on config change

### ISSUE THREAD

**Issue by bixu** [honeycombio/helm-charts#83]
We saw an issue recently with the Helm chart for Refinery where adding some new hashing fields to the config didn't trigger a restart, and resulted in weird behavior from the cluster that forced us to manually restart the Refinery pods.

**Versions**

Chart: 1.3.0
Helm: ArgoCD v2.0.3+8
Kubernetes cluster: EKS 1.18.20
Refinery Version:  "v1.6.1@sha256:e742af48b2ac1eb6b0116246780eb7e4942f0251152742990def677d853a129a"

**Steps to reproduce**

1. Add a new field to the `values.yml` override for hashing field config
2. Deploy the new config
3. Notice that Refinery pods do not restart to consume the new config

**Comment by MikeGoldsmith** [comment]
Hey @bixu - thanks for the bug report. We'll look at this soon.

**Comment by bixu** [comment]
@MikeGoldsmith, I'm considering another similar config change in the next working day or so. What kind of data collection would you recommend I do, in case we see the same pathology on this maintenance event?

**Comment by MikeGoldsmith** [comment]
Hey @bixu. During my testing I've found that changes to configuration result in different restart behaviour.

- Changes to the refinery config section do cause pods to restart during `helm upgrade`
- Changes to the refinery rules section do not cause pods to restart. However, refinery live-reloads the rules configuration to rules changes should still be applied without a pod restart

I'm working on whether we should have consistent restart behaviour for both config files. Whether pods are restarted is based on the checksum value calculated from configmap.yaml on the deployment annotation changing. I'm unsure for the moment why config changes cause that trigger and rules changes do not. I'll keep investigating.

**Comment by MikeGoldsmith** [comment]
@bixu can you share which config values you changed previously and expect to change in the near future?

**Comment by MikeGoldsmith** [comment]
Hey @bixu - I've updated our docs to indicate what config changes are expected to cause pods to recycle. Please re-open if this doesn't address your query.

**Comment by bixu** [comment]
> @bixu can you share which config values you changed previously and expect to change in the near future?

Hi @MikeGoldsmith, we had added two fields to the field list for hashing. We had concerns because we saw un-balanced memory consumption across Refinery pods immediately after the config update. Perhaps we didn't wait long enough for in-flight traces to balance across the cluster. How long should we expect to wait for the cluster to balance?

**Comment by MikeGoldsmith** [comment]
Hi @bixu 

Sampler FieldList (Dynamic or EMADynamic) does not determine how traces are sharded across the cluster. The SHA1 hash of the TraceID is used to distribute traces across nodes. If you haven't changed the number of cluster nodes and the nodes have not restarted, I don't see a reason for unbalanced trace distribution.

If you've updated the FieldList, maybe you've added a high cardinality field that's generating a high number of combinations? Can you share more about what your field list was previously and was update to, and specifically what values you expect from the new fields?

Thanks

**Comment by bixu** [comment]
@MikeGoldsmith, really sorry about the very late reply here, I missed this last request from you.

We were moving from this `rules` config:

```yaml
    FieldList:
      - http.method
      - http.status
      - service.name
```

to this:

```yaml
    FieldList:
      - http.method
      - http.status
      - service.name
      - messaging.kafka.partition
      - messaging.destination
      - rpc.grpc.status_code
```
