### ISSUE TITLE
Add the ability to use existingSecrets for Secure Tenancy Chart

### ISSUE THREAD

**Issue by McSick** [honeycombio/helm-charts#93]
**Is your feature request related to a problem? Please describe.**
If you have an existing way to manage secrets, the helm chart will overwrite your secrets.

**Describe the solution you'd like**
Offer optional "existingSecret" config property that will allow you to specify your secrets and not create them in the secrets.yaml.

**Describe alternatives you've considered**

**Additional context**

**Comment by JamieDanielson** [comment]
Just a note for context, this is already being used for the Honeycomb Kubernetes chart, and the request is to use the same sort of logic for Secure Tenancy chart.

**Comment by vreynolds** [comment]
👋
